version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::381491927793:user/aws-sam-cli-managed-dev-pipeline-resou-PipelineUser-wZeyZAmvZdwd"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::381491927793:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-mM6EyM01mOJa"
cloudformation_execution_role = "arn:aws:iam::381491927793:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-uiBkpCJXlPVW"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-4pjem4ui6kkd"
image_repository = ""
region = "us-east-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::381491927793:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-jGQ5ogm8mhTY"
cloudformation_execution_role = "arn:aws:iam::381491927793:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-6oUMKbnWSMBV"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-prvcepv11hag"
image_repository = ""
region = "us-east-1"
